name: tasko
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# Application version.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  timezone: ^0.10.0
  video_player: ^2.9.2
  flutter_screenutil: ^5.9.0
  flutter_upi_pay: ^0.0.2
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  google_places_flutter: ^2.0.8
  http: ^1.2.1
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  provider: ^6.1.1
  readmore: ^3.0.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_core: ^25.1.39
  syncfusion_flutter_sliders: ^25.1.39
  toggle_switch: ^2.1.0
  supabase_flutter: ^2.8.3
  flutter_local_notifications: ^18.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  # Asset declarations.
  assets:
    - assets/
    - assets/Dashboard/
    - assets/LandingPage/
    - assets/DetailsPage/
    - .env

flutter_icons:
  android: true
  remove_alpha_ios: true
  image_path: "assets/tasko_logo.png"
